// Which staff member generated which revenue, over a season.
//
// Pure TS (no Supabase, no DOM) so the attribution rule is unit-testable; the
// admin page batches the reads and hands the rows in.
//
// The shop's rule, and the reason each half of it exists:
//
//   - Only an instructor can deliver a course, so only a rostered instructor
//     earns from one. A guide on a course is assisting.
//   - An instructor or a guide can lead divers on anything else, so either
//     earns from a dive or an adventure.
//   - Support never earns, on any kind. It is an unpaid role.
//   - When two people qualify on the same event -- a course big enough to
//     split between instructors, a dive needing a second guide -- they split
//     its revenue evenly.
//
// Who is paid is inferred from the roster rather than recorded: anyone rostered
// in an earning role shares the event. The shop knows which of its crew it
// actually pays; the app does not need to, and a flag nobody maintains would
// be worse than no flag at all.
//
// Revenue is the event's BASE PRICE times its confirmed heads -- the course fee
// or the dive fee, per student. Deliberately not the money received: what a
// person generated is a property of the work they did, not of whether an
// invoice has been settled, and a course whose balance lands in November did
// not stop being June's teaching. It is also deliberately not the booking's
// full total -- gear rental, transport and add-ons are the shop's margin on
// hire and logistics, not something the instructor generated by teaching.
//
// Each booking's base comes from the charge snapshot taken at registration, so
// a later catalogue price change cannot retroactively rewrite what a season
// earned. Bookings predating that snapshot fall back to the event's current
// catalogue price.
import { isInstructorLed, type EventKind } from './event-kinds'
import type { DutyRole } from '../types/database'

export interface RevenueEvent {
  id: string
  kind: EventKind
  admin_title: string | null
  display_title: string | null
  start_date: string | null
  end_date: string | null
  course_days: string[] | null
  cancelled_at: string | null
  /** Catalogue base price per head, resolved from the linked prices row. Used
   *  only for bookings with no charge snapshot of their own. */
  base_price: number | null
}

export interface RevenueDuty {
  event_id: string | null
  assignee_id: string
  role: DutyRole
}

/** The slice of `bookings.details` this module reads. */
export interface RevenueBookingDetails {
  charges?: Array<{ kind?: string | null; amount?: number | null }> | null
}

export interface RevenueBooking {
  id: string
  event_id: string | null
  status: string
  details: RevenueBookingDetails | null
}

export interface RevenuePerson {
  id: string
  name: string | null
  nickname: string | null
}

/** True when someone working `role` on a `kind` event earns a share of it. */
export function earnsRevenue(kind: EventKind, role: DutyRole): boolean {
  if (role === 'support') return false
  if (isInstructorLed(kind)) return role === 'instructor'
  return role === 'instructor' || role === 'guide'
}

/**
 * What this booking paid for the event itself: the `base` line of its charge
 * snapshot, or the event's catalogue price when the booking predates
 * snapshotting. Gear, rooms, transport, add-ons and card surcharges are all
 * other lines and are deliberately left out.
 */
export function bookingBase(
  details: RevenueBookingDetails | null | undefined,
  catalogPrice: number | null,
): number {
  const lines = details?.charges
  if (Array.isArray(lines)) {
    const base = lines
      .filter(l => l?.kind === 'base')
      .reduce((sum, l) => sum + (Number(l?.amount) || 0), 0)
    if (base) return base
  }
  return Number(catalogPrice) || 0
}

/** One event as it appears in a person's season, already carrying their cut. */
export interface EventRevenue {
  eventId: string
  kind: EventKind
  title: string
  /** Grouping label — the course type ("OW", "AOW") or the dive's name. */
  category: string
  firstDay: string | null
  lastDay: string | null
  /** YYYY-MM of the first day — the month the event is booked to. */
  month: string | null
  /** Confirmed bookings on the event. Not divided between crew: it is a count
   *  of who they worked with, not a share of anything. */
  students: number
  /** Base price × confirmed heads, for the whole event. */
  revenue: number
  /** Crew rostered in a role that earns from this event. */
  earnerIds: string[]
  /** revenue / earnerIds.length — one person's cut. Zero when nobody earns. */
  share: number
  /** True when the event's last day has passed in the shop's timezone. */
  completed: boolean
}

export interface MonthRevenue {
  month: string
  taughtEvents: number
  ledEvents: number
  students: number
  revenue: number
  /** The events behind the counts, for the row's expanded view. */
  events: EventRevenue[]
}

export interface CategoryRevenue {
  kind: EventKind
  category: string
  events: number
  students: number
  revenue: number
}

/** Courses on one side, everything led rather than taught on the other. */
export interface GroupRevenue {
  taught: boolean
  events: number
  students: number
  revenue: number
  categories: CategoryRevenue[]
}

export interface PersonRevenue {
  personId: string
  name: string
  months: MonthRevenue[]
  groups: GroupRevenue[]
  events: EventRevenue[]
  completed: { events: number; students: number; revenue: number }
  upcoming: { events: number; students: number; revenue: number }
}

export interface StaffRevenueReport {
  season: number
  people: PersonRevenue[]
  /** Events that took bookings but had nobody rostered who could earn from
   *  them. Their revenue belongs to no one, so it is held here rather than
   *  silently dropped — otherwise the per-person columns quietly fail to
   *  reconcile with what the shop actually sold. */
  unattributed: {
    revenue: number
    events: EventRevenue[]
  }
}

export interface BuildStaffRevenueInput {
  season: number
  events: RevenueEvent[]
  duties: RevenueDuty[]
  bookings: RevenueBooking[]
  people: RevenuePerson[]
  /** Today in the shop's timezone, YYYY-MM-DD — pass todayIso(). */
  today: string
}

function displayName(p: RevenuePerson): string {
  return p.nickname || p.name || p.id
}

/** First and last calendar day of an event, whichever columns carry them. */
export function eventSpan(e: RevenueEvent): { first: string | null; last: string | null } {
  const days = (e.course_days ?? []).filter(Boolean).slice().sort()
  if (days.length) return { first: days[0], last: days[days.length - 1] }
  const first = e.start_date ?? null
  return { first, last: e.end_date ?? first }
}

function titleOf(e: RevenueEvent): string {
  return e.display_title || e.admin_title || e.id
}

/**
 * Roll duties and bookings up into per-person season figures.
 *
 * Cancelled events are dropped entirely — a cancelled event's money is a
 * refund story, told by the Audits page, not revenue anyone generated.
 * Cancelled and pending bookings are dropped for the same reason: only a
 * confirmed seat is a sale.
 */
export function buildStaffRevenue(input: BuildStaffRevenueInput): StaffRevenueReport {
  const { season, today } = input
  const personById = new Map(input.people.map(p => [p.id, p]))
  const eventById = new Map(input.events.map(e => [e.id, e]))

  const soldByEvent = new Map<string, { students: number; revenue: number }>()
  for (const b of input.bookings) {
    if (b.status !== 'confirmed' || !b.event_id) continue
    const bucket = soldByEvent.get(b.event_id) ?? { students: 0, revenue: 0 }
    bucket.students += 1
    bucket.revenue += bookingBase(b.details, eventById.get(b.event_id)?.base_price ?? null)
    soldByEvent.set(b.event_id, bucket)
  }

  const dutiesByEvent = new Map<string, RevenueDuty[]>()
  for (const d of input.duties) {
    if (!d.event_id) continue
    const list = dutiesByEvent.get(d.event_id)
    if (list) list.push(d)
    else dutiesByEvent.set(d.event_id, [d])
  }

  const perPerson = new Map<string, EventRevenue[]>()
  const unattributedEvents: EventRevenue[] = []

  for (const e of input.events) {
    if (e.cancelled_at) continue
    const { first, last } = eventSpan(e)
    if (!first || first.slice(0, 4) !== String(season)) continue

    const sold = soldByEvent.get(e.id) ?? { students: 0, revenue: 0 }

    const earnerIds = [...new Set(
      (dutiesByEvent.get(e.id) ?? [])
        .filter(d => earnsRevenue(e.kind, d.role))
        .map(d => d.assignee_id),
    )].sort()

    const row: EventRevenue = {
      eventId: e.id,
      kind: e.kind,
      title: titleOf(e),
      category: e.admin_title || titleOf(e),
      firstDay: first,
      lastDay: last,
      month: first.slice(0, 7),
      students: sold.students,
      revenue: sold.revenue,
      earnerIds,
      share: earnerIds.length ? sold.revenue / earnerIds.length : 0,
      completed: !!last && last < today,
    }

    if (!earnerIds.length) {
      // Only worth surfacing when there is something to account for. An event
      // nobody booked and nobody was rostered for is not a roster gap.
      if (sold.students > 0) unattributedEvents.push(row)
      continue
    }
    for (const id of earnerIds) {
      const list = perPerson.get(id)
      if (list) list.push(row)
      else perPerson.set(id, [row])
    }
  }

  const people: PersonRevenue[] = [...perPerson.entries()].map(([personId, events]) => {
    const sorted = [...events].sort((a, b) => (a.firstDay ?? '').localeCompare(b.firstDay ?? ''))
    const done = sorted.filter(e => e.completed)

    const months = new Map<string, MonthRevenue>()
    const categories = new Map<string, CategoryRevenue>()
    for (const e of done) {
      if (e.month) {
        const m = months.get(e.month) ?? {
          month: e.month, taughtEvents: 0, ledEvents: 0, students: 0, revenue: 0, events: [],
        }
        if (isInstructorLed(e.kind)) m.taughtEvents += 1
        else m.ledEvents += 1
        m.students += e.students
        m.revenue += e.share
        m.events.push(e)
        months.set(e.month, m)
      }
      const key = `${e.kind}:${e.category}`
      const c = categories.get(key) ?? { kind: e.kind, category: e.category, events: 0, students: 0, revenue: 0 }
      c.events += 1
      c.students += e.students
      c.revenue += e.share
      categories.set(key, c)
    }

    const groups: GroupRevenue[] = [true, false].map(taught => {
      const mine = [...categories.values()]
        .filter(c => isInstructorLed(c.kind) === taught)
        .sort((a, b) => b.revenue - a.revenue || a.category.localeCompare(b.category))
      return {
        taught,
        events: mine.reduce((s, c) => s + c.events, 0),
        students: mine.reduce((s, c) => s + c.students, 0),
        revenue: mine.reduce((s, c) => s + c.revenue, 0),
        categories: mine,
      }
    }).filter(g => g.events > 0)

    const sum = (list: EventRevenue[]) => ({
      events: list.length,
      students: list.reduce((s, e) => s + e.students, 0),
      revenue: list.reduce((s, e) => s + e.share, 0),
    })

    return {
      personId,
      name: displayName(personById.get(personId) ?? { id: personId, name: null, nickname: null }),
      months: [...months.values()].sort((a, b) => a.month.localeCompare(b.month)),
      groups,
      events: sorted,
      completed: sum(done),
      upcoming: sum(sorted.filter(e => !e.completed)),
    }
  }).sort((a, b) => b.completed.revenue - a.completed.revenue || a.name.localeCompare(b.name))

  const unattributedDone = unattributedEvents.filter(e => e.completed)
  return {
    season,
    people,
    unattributed: {
      revenue: unattributedDone.reduce((s, e) => s + e.revenue, 0),
      events: unattributedDone.sort((a, b) => (a.firstDay ?? '').localeCompare(b.firstDay ?? '')),
    },
  }
}
