import { supabase } from './supabase'
import { siteConfig } from '../config/site'
import type { TripReferral, ReferralStatus, KickbackStatus } from '../types/database'

// Admin data layer for the referral pipeline + kickback ledger. Divers create
// referrals through the express_trip_interest RPC and read their own via the
// my_trip_referrals view; this module is the admin side, reading/writing the
// base trip_referrals table (gated by the "admin manage" RLS policy).

/** The contact fields an admin needs to broker the intro to the partner. */
export interface ReferralDiver {
  id: string
  name: string | null
  nickname: string | null
  email: string | null
  contact_id: string | null
}

export interface AdminReferral extends TripReferral {
  diver: ReferralDiver | null
}

export async function fetchReferralsWithDivers(): Promise<AdminReferral[]> {
  const { data: refs, error } = await supabase
    .from('trip_referrals')
    .select('*')
    .order('created_at', { ascending: false })
  if (error) throw error
  const rows = (refs ?? []) as TripReferral[]

  const diverIds = [...new Set(rows.map(r => r.diver_id))]
  let byId = new Map<string, ReferralDiver>()
  if (diverIds.length > 0) {
    const { data: profiles, error: pErr } = await supabase
      .from('profiles')
      .select('id, name, nickname, email, contact_id')
      .in('id', diverIds)
    if (pErr) throw pErr
    byId = new Map((profiles ?? []).map(p => [(p as ReferralDiver).id, p as ReferralDiver]))
  }

  return rows.map(r => ({ ...r, diver: byId.get(r.diver_id) ?? null }))
}

/** How many referrals are sitting at 'interested' (awaiting an intro) — the
 *  admin's "new interest" badge. A head/count query, no rows transferred. */
export async function countInterestedReferrals(): Promise<number> {
  const { count, error } = await supabase
    .from('trip_referrals')
    .select('id', { count: 'exact', head: true })
    .eq('status', 'interested')
  if (error) throw error
  return count ?? 0
}

export interface KickbackByCurrency {
  currency: string
  /** Kickback we've collected (kickback_status = received). */
  received: number
  /** Kickback we're still owed (booked, not yet received). */
  outstanding: number
}

/**
 * Roll the kickback ledger up by currency: how much we've received vs how much
 * is still outstanding. Only referrals that actually converted (a non-null
 * kickback_amount) count; cancelled/interested ones contribute nothing.
 * Ordered by currency so the display is stable.
 */
export function summarizeKickbacks(referrals: AdminReferral[]): KickbackByCurrency[] {
  const byCur = new Map<string, { received: number; outstanding: number }>()
  for (const r of referrals) {
    if (r.kickback_amount == null) continue
    const cur = r.booked_currency || siteConfig.locale.currency
    const acc = byCur.get(cur) ?? { received: 0, outstanding: 0 }
    if (r.kickback_status === 'received') acc.received += r.kickback_amount
    else acc.outstanding += r.kickback_amount
    byCur.set(cur, acc)
  }
  return [...byCur.entries()]
    .map(([currency, v]) => ({ currency, ...v }))
    .sort((a, b) => a.currency.localeCompare(b.currency))
}

export async function updateReferral(
  id: string,
  patch: Partial<{
    status: ReferralStatus
    booked_amount: number | null
    booked_currency: string | null
    kickback_rate: number | null
    kickback_status: KickbackStatus
    received_at: string | null
    admin_notes: string | null
  }>,
): Promise<void> {
  const { error } = await supabase.from('trip_referrals').update(patch).eq('id', id)
  if (error) throw error
}

/**
 * Record that a referral converted into a booking at the partner shop. Snapshots
 * the kickback rate at booking time so later rate changes on the trip don't
 * rewrite history; kickback_amount is generated by the DB from amount * rate.
 */
export async function recordReferralBooking(args: {
  id: string
  bookedAmount: number
  bookedCurrency: string
  kickbackRate: number
}): Promise<void> {
  await updateReferral(args.id, {
    status: 'booked',
    booked_amount: args.bookedAmount,
    booked_currency: args.bookedCurrency,
    kickback_rate: args.kickbackRate,
  })
}

/** Move the kickback through pending → invoiced → received; stamp received_at
 *  when (and only when) it lands on received. */
export async function setKickbackStatus(id: string, status: KickbackStatus): Promise<void> {
  await updateReferral(id, {
    kickback_status: status,
    received_at: status === 'received' ? new Date().toISOString() : null,
  })
}
