import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

// virtual:pwa-register/react is generated by vite-plugin-pwa at build time.
// Vitest doesn't run that plugin, so the import would fail to resolve in
// any code that calls useRegisterSW (the AppShell update banner). Resolve
// it to an inert stub here — individual tests can vi.mock() over the top
// to assert behavior.
const stubVirtualPWARegister = () => ({
  name: 'stub-virtual-pwa-register',
  resolveId(id: string) {
    if (id === 'virtual:pwa-register/react') return '\0virtual:pwa-register/react'
  },
  load(id: string) {
    if (id === '\0virtual:pwa-register/react') {
      return `export function useRegisterSW() {
        return {
          needRefresh: [false, () => {}],
          offlineReady: [false, () => {}],
          updateServiceWorker: async () => {},
        }
      }`
    }
  },
})

export default defineConfig({
  plugins: [react(), stubVirtualPWARegister()],
  test: {
    projects: [
      {
        extends: true,
        test: {
          name: 'unit',
          globals: true,
          environment: 'happy-dom',
          setupFiles: ['./tests/setup.unit.ts'],
          // supabase/functions/ tests cover the pure-TS handler /
          // helper modules (handler.ts, _shared/*.ts) — the Deno entry
          // index.ts uses jsr:/npm: specifiers and is NOT
          // vitest-importable, so tests only import the handler. See
          // create-registration/handler.ts for the dep-injection
          // pattern these tests rely on.
          include: [
            'src/**/*.test.{ts,tsx}',
            'workers/**/*.test.ts',
            'supabase/functions/**/*.test.ts',
          ],
          css: false,
        },
      },
      {
        extends: true,
        test: {
          name: 'integration',
          globals: true,
          environment: 'node',
          globalSetup: ['./tests/global-setup.integration.ts'],
          setupFiles: ['./tests/setup.integration.ts'],
          include: ['tests/integration/**/*.test.ts'],
          testTimeout: 30_000,
          hookTimeout: 30_000,
          fileParallelism: false,
        },
      },
      {
        // Black-box "attacker" probes. Same live local stack as the
        // integration suite, but every request goes out via native
        // fetch() — no supabase-js abstraction, so we exercise the
        // exact wire shape an external attacker would send (raw
        // query operators, PostgREST PUT vs PATCH, CORS preflights,
        // edge-function HTTP envelope, etc.). Each fix from
        // docs/security-audit.md lands a matching probe file.
        extends: true,
        test: {
          name: 'security',
          globals: true,
          environment: 'node',
          globalSetup: ['./tests/global-setup.integration.ts'],
          setupFiles: ['./tests/setup.integration.ts'],
          include: ['tests/security/**/*.test.ts'],
          testTimeout: 30_000,
          hookTimeout: 30_000,
          fileParallelism: false,
        },
      },
    ],
  },
})
