import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest'
import { renderHook, act } from '@testing-library/react'

// virtual:pwa-register/react is generated by vite-plugin-pwa at build time
// and has no module to resolve under vitest. Stub it before importing the
// hook so the import path resolves.
const useRegisterSWMock = vi.fn()
vi.mock('virtual:pwa-register/react', () => ({
  useRegisterSW: (opts: unknown) => useRegisterSWMock(opts),
}))

// Import after the mock is registered.
const { usePWAUpdate } = await import('./usePWAUpdate')

beforeEach(() => {
  useRegisterSWMock.mockReset()
  vi.useFakeTimers()
})

afterEach(() => {
  vi.useRealTimers()
})

function configureMock(opts: { needRefresh: boolean; updateServiceWorker?: ReturnType<typeof vi.fn> } = { needRefresh: false }) {
  const updateServiceWorker = opts.updateServiceWorker ?? vi.fn().mockResolvedValue(undefined)
  let captured: { onRegisteredSW?: (url: string, reg: ServiceWorkerRegistration | undefined) => void } = {}
  useRegisterSWMock.mockImplementation((options: typeof captured) => {
    captured = options ?? {}
    return {
      needRefresh: [opts.needRefresh, vi.fn()],
      offlineReady: [false, vi.fn()],
      updateServiceWorker,
    }
  })
  return { updateServiceWorker, getCaptured: () => captured }
}

describe('usePWAUpdate', () => {
  it('returns needRefresh=false when no update is waiting', () => {
    configureMock({ needRefresh: false })
    const { result } = renderHook(() => usePWAUpdate())
    expect(result.current.needRefresh).toBe(false)
  })

  it('returns needRefresh=true when the SW has a waiting update', () => {
    configureMock({ needRefresh: true })
    const { result } = renderHook(() => usePWAUpdate())
    expect(result.current.needRefresh).toBe(true)
  })

  it('update() reloads via updateServiceWorker(true)', async () => {
    const { updateServiceWorker } = configureMock({ needRefresh: true })
    const { result } = renderHook(() => usePWAUpdate())
    await act(async () => { await result.current.update() })
    expect(updateServiceWorker).toHaveBeenCalledWith(true)
  })

  it('does NOT expose a dismiss helper — the banner has no Later button', () => {
    // A dismiss path would let users keep an out-of-date PWA running
    // against a migrated backend. Update is the only action.
    configureMock({ needRefresh: true })
    const { result } = renderHook(() => usePWAUpdate())
    expect((result.current as { dismiss?: unknown }).dismiss).toBeUndefined()
  })

  it('schedules a periodic registration.update() — the polling cadence for long-lived tabs', () => {
    // Without polling, a PWA kept open across days only re-checks for new
    // builds on tab focus. The polling is what makes the banner appear
    // for users who never close the tab.
    const { getCaptured } = configureMock({ needRefresh: false })
    renderHook(() => usePWAUpdate())
    const update = vi.fn().mockResolvedValue(undefined)
    const fakeRegistration = { update } as unknown as ServiceWorkerRegistration
    getCaptured().onRegisteredSW?.('/sw.js', fakeRegistration)

    expect(update).not.toHaveBeenCalled()
    vi.advanceTimersByTime(30 * 60 * 1000)
    expect(update).toHaveBeenCalledOnce()
    vi.advanceTimersByTime(30 * 60 * 1000)
    expect(update).toHaveBeenCalledTimes(2)
  })

  it('does nothing when registration is undefined (e.g. SW disabled)', () => {
    const { getCaptured } = configureMock({ needRefresh: false })
    renderHook(() => usePWAUpdate())
    expect(() => getCaptured().onRegisteredSW?.('/sw.js', undefined)).not.toThrow()
  })
})
