-- A starter catalog of what divers actually report seeing.
--
-- Reference data, not shop content. A scientific name is the same in Kenting,
-- Okinawa and Palau, so this ships with the app the way certification levels
-- do — a shop that forks FunDive starts with a catalog its divers can file
-- against on day one instead of a blank table that makes the wildlife field
-- useless until somebody types a hundred species in.
--
-- The list is chosen for the water this app was written for — the Indo-Pacific
-- reefs off Taiwan, Japan and the Philippines — and is deliberately shallow in
-- places. Where a diver can reasonably tell the species (a whale shark, a
-- moorish idol) there is a species. Where they usually cannot (a goby, a
-- damselfish, a soft coral) the entry is the family or the order, because a
-- catalog that only offers species pushes an honest "some kind of goby" into
-- either a guess or a blank. Staff add what their own site turns up.
--
-- NAMES ARE OMITTED RATHER THAN GUESSED. A taxon with no name in a language
-- renders as its scientific name, which is correct and readable; a plausible
-- but wrong common name is neither, and it would take the unique index on
-- (lang, name) with it — locking the mistake in as the one thing that word can
-- mean. Where the Japanese or Chinese name for an entry was not certain, the
-- row is simply not there, and staff fill it in from the admin page.
--
-- Inserted in rank order, parents first: `parent_id` is resolved by looking the
-- parent's scientific name up in what is already in the table, so each tier has
-- to be its own statement.

-- Phyla
insert into public.taxa (rank, scientific_name, parent_id)
select v.rank, v.scientific_name, p.id
from (values
  ('phylum', 'Cnidaria', null),
  ('phylum', 'Echinodermata', null)
) as v(rank, scientific_name, parent_name)
left join public.taxa p on lower(p.scientific_name) = lower(v.parent_name);

-- Classes
insert into public.taxa (rank, scientific_name, parent_id)
select v.rank, v.scientific_name, p.id
from (values
  ('class', 'Cephalopoda', null),
  ('class', 'Gastropoda', null),
  ('class', 'Bivalvia', null),
  ('class', 'Scyphozoa', 'Cnidaria'),
  ('class', 'Echinoidea', 'Echinodermata'),
  ('class', 'Asteroidea', 'Echinodermata'),
  ('class', 'Holothuroidea', 'Echinodermata'),
  ('class', 'Crinoidea', 'Echinodermata'),
  ('class', 'Ophiuroidea', 'Echinodermata'),
  ('subclass', 'Elasmobranchii', null)
) as v(rank, scientific_name, parent_name)
left join public.taxa p on lower(p.scientific_name) = lower(v.parent_name);

-- Superorders
insert into public.taxa (rank, scientific_name, parent_id)
select v.rank, v.scientific_name, p.id
from (values
  ('superorder', 'Selachimorpha', 'Elasmobranchii'),
  ('superorder', 'Batoidea', 'Elasmobranchii')
) as v(rank, scientific_name, parent_name)
left join public.taxa p on lower(p.scientific_name) = lower(v.parent_name);

-- Orders
insert into public.taxa (rank, scientific_name, parent_id)
select v.rank, v.scientific_name, p.id
from (values
  ('order', 'Testudines', null),
  ('order', 'Nudibranchia', 'Gastropoda'),
  ('order', 'Octopoda', 'Cephalopoda'),
  ('order', 'Sepiida', 'Cephalopoda'),
  ('order', 'Scleractinia', 'Cnidaria'),
  ('order', 'Alcyonacea', 'Cnidaria')
) as v(rank, scientific_name, parent_name)
left join public.taxa p on lower(p.scientific_name) = lower(v.parent_name);

-- Families and genera
insert into public.taxa (rank, scientific_name, parent_id)
select v.rank, v.scientific_name, p.id
from (values
  ('family', 'Cheloniidae', 'Testudines'),
  ('family', 'Rhincodontidae', 'Selachimorpha'),
  ('family', 'Carcharhinidae', 'Selachimorpha'),
  ('family', 'Sphyrnidae', 'Selachimorpha'),
  ('family', 'Mobulidae', 'Batoidea'),
  ('family', 'Dasyatidae', 'Batoidea'),
  ('family', 'Myliobatidae', 'Batoidea'),
  ('family', 'Chaetodontidae', null),
  ('family', 'Pomacanthidae', null),
  ('family', 'Pomacentridae', null),
  ('family', 'Labridae', null),
  ('family', 'Scaridae', null),
  ('family', 'Serranidae', null),
  ('family', 'Muraenidae', null),
  ('family', 'Scorpaenidae', null),
  ('family', 'Synanceiidae', null),
  ('family', 'Antennariidae', null),
  ('family', 'Syngnathidae', null),
  ('family', 'Ostraciidae', null),
  ('family', 'Tetraodontidae', null),
  ('family', 'Diodontidae', null),
  ('family', 'Balistidae', null),
  ('family', 'Acanthuridae', null),
  ('family', 'Zanclidae', null),
  ('family', 'Apogonidae', null),
  ('family', 'Blenniidae', null),
  ('family', 'Gobiidae', null),
  ('family', 'Holocentridae', null),
  ('family', 'Lutjanidae', null),
  ('family', 'Haemulidae', null),
  ('family', 'Caesionidae', null),
  ('family', 'Siganidae', null),
  ('family', 'Mullidae', null),
  ('family', 'Carangidae', null),
  ('family', 'Sphyraenidae', null),
  ('family', 'Molidae', null),
  ('family', 'Loliginidae', 'Cephalopoda'),
  ('family', 'Palinuridae', null),
  ('family', 'Stenopodidae', null),
  ('family', 'Delphinidae', null),
  ('family', 'Balaenopteridae', null),
  ('family', 'Physeteridae', null),
  ('genus', 'Hippocampus', 'Syngnathidae'),
  ('genus', 'Tridacna', 'Bivalvia'),
  ('genus', 'Acropora', 'Scleractinia'),
  ('genus', 'Porites', 'Scleractinia'),
  ('genus', 'Laticauda', null)
) as v(rank, scientific_name, parent_name)
left join public.taxa p on lower(p.scientific_name) = lower(v.parent_name);

-- Species
insert into public.taxa (rank, scientific_name, parent_id)
select v.rank, v.scientific_name, p.id
from (values
  ('species', 'Chelonia mydas', 'Cheloniidae'),
  ('species', 'Eretmochelys imbricata', 'Cheloniidae'),
  ('species', 'Rhincodon typus', 'Rhincodontidae'),
  ('species', 'Triaenodon obesus', 'Carcharhinidae'),
  ('species', 'Carcharhinus melanopterus', 'Carcharhinidae'),
  ('species', 'Sphyrna lewini', 'Sphyrnidae'),
  ('species', 'Mobula alfredi', 'Mobulidae'),
  ('species', 'Mobula birostris', 'Mobulidae'),
  ('species', 'Taeniura lymma', 'Dasyatidae'),
  ('species', 'Aetobatus ocellatus', 'Myliobatidae'),
  ('species', 'Amphiprion clarkii', 'Pomacentridae'),
  ('species', 'Amphiprion ocellaris', 'Pomacentridae'),
  ('species', 'Pomacanthus imperator', 'Pomacanthidae'),
  ('species', 'Chaetodon auriga', 'Chaetodontidae'),
  ('species', 'Heniochus acuminatus', 'Chaetodontidae'),
  ('species', 'Zanclus cornutus', 'Zanclidae'),
  ('species', 'Cheilinus undulatus', 'Labridae'),
  ('species', 'Bolbometopon muricatum', 'Scaridae'),
  ('species', 'Plectropomus leopardus', 'Serranidae'),
  ('species', 'Gymnothorax javanicus', 'Muraenidae'),
  ('species', 'Pterois volitans', 'Scorpaenidae'),
  ('species', 'Synanceia verrucosa', 'Synanceiidae'),
  ('species', 'Ostracion cubicus', 'Ostraciidae'),
  ('species', 'Mola mola', 'Molidae'),
  ('species', 'Sepioteuthis lessoniana', 'Loliginidae'),
  ('species', 'Hexabranchus sanguineus', 'Nudibranchia'),
  ('species', 'Acanthaster planci', 'Asteroidea'),
  ('species', 'Stenopus hispidus', 'Stenopodidae'),
  ('species', 'Megaptera novaeangliae', 'Balaenopteridae'),
  ('species', 'Physeter macrocephalus', 'Physeteridae')
) as v(rank, scientific_name, parent_name)
left join public.taxa p on lower(p.scientific_name) = lower(v.parent_name);


-- Vernacular names. Every seeded name is the primary one for its language,
-- because a taxon carrying exactly one name per language has nothing to
-- choose between and the flag has to be set for later additions to be able to
-- displace it.
insert into public.taxon_names (taxon_id, lang, name, is_primary)
select t.id, v.lang, v.name, true
from (values
  ('Cnidaria', 'en', 'cnidarian'),
  ('Cnidaria', 'ja', '刺胞動物'),
  ('Cnidaria', 'zh-TW', '刺胞動物'),
  ('Echinodermata', 'en', 'echinoderm'),
  ('Echinodermata', 'ja', '棘皮動物'),
  ('Echinodermata', 'zh-TW', '棘皮動物'),
  ('Cephalopoda', 'en', 'cephalopod'),
  ('Cephalopoda', 'ja', '頭足類'),
  ('Cephalopoda', 'zh-TW', '頭足類'),
  ('Gastropoda', 'en', 'sea snail or slug'),
  ('Gastropoda', 'ja', '腹足類'),
  ('Gastropoda', 'zh-TW', '腹足類'),
  ('Bivalvia', 'en', 'bivalve'),
  ('Bivalvia', 'ja', '二枚貝'),
  ('Bivalvia', 'zh-TW', '雙殼貝'),
  ('Scyphozoa', 'en', 'jellyfish'),
  ('Scyphozoa', 'ja', 'クラゲ'),
  ('Scyphozoa', 'zh-TW', '水母'),
  ('Echinoidea', 'en', 'sea urchin'),
  ('Echinoidea', 'ja', 'ウニ'),
  ('Echinoidea', 'zh-TW', '海膽'),
  ('Asteroidea', 'en', 'sea star'),
  ('Asteroidea', 'ja', 'ヒトデ'),
  ('Asteroidea', 'zh-TW', '海星'),
  ('Holothuroidea', 'en', 'sea cucumber'),
  ('Holothuroidea', 'ja', 'ナマコ'),
  ('Holothuroidea', 'zh-TW', '海參'),
  ('Crinoidea', 'en', 'feather star'),
  ('Crinoidea', 'ja', 'ウミシダ'),
  ('Crinoidea', 'zh-TW', '海百合'),
  ('Ophiuroidea', 'en', 'brittle star'),
  ('Ophiuroidea', 'ja', 'クモヒトデ'),
  ('Ophiuroidea', 'zh-TW', '陽燧足'),
  ('Elasmobranchii', 'en', 'shark or ray'),
  ('Elasmobranchii', 'ja', '板鰓類'),
  ('Elasmobranchii', 'zh-TW', '板鰓類'),
  ('Selachimorpha', 'en', 'shark'),
  ('Selachimorpha', 'ja', 'サメ'),
  ('Selachimorpha', 'zh-TW', '鯊魚'),
  ('Batoidea', 'en', 'ray'),
  ('Batoidea', 'ja', 'エイ'),
  ('Batoidea', 'zh-TW', '魟魚'),
  ('Testudines', 'en', 'turtle'),
  ('Testudines', 'ja', 'カメ'),
  ('Testudines', 'zh-TW', '龜'),
  ('Nudibranchia', 'en', 'nudibranch'),
  ('Nudibranchia', 'ja', 'ウミウシ'),
  ('Nudibranchia', 'zh-TW', '海蛞蝓'),
  ('Octopoda', 'en', 'octopus'),
  ('Octopoda', 'ja', 'タコ'),
  ('Octopoda', 'zh-TW', '章魚'),
  ('Sepiida', 'en', 'cuttlefish'),
  ('Sepiida', 'ja', 'コウイカ'),
  ('Sepiida', 'zh-TW', '烏賊'),
  ('Scleractinia', 'en', 'hard coral'),
  ('Scleractinia', 'ja', 'イシサンゴ'),
  ('Scleractinia', 'zh-TW', '石珊瑚'),
  ('Alcyonacea', 'en', 'soft coral'),
  ('Alcyonacea', 'ja', 'ソフトコーラル'),
  ('Alcyonacea', 'zh-TW', '軟珊瑚'),
  ('Cheloniidae', 'en', 'sea turtle'),
  ('Cheloniidae', 'ja', 'ウミガメ'),
  ('Cheloniidae', 'zh-TW', '海龜'),
  ('Carcharhinidae', 'en', 'requiem shark'),
  ('Carcharhinidae', 'ja', 'メジロザメ科'),
  ('Carcharhinidae', 'zh-TW', '真鯊科'),
  ('Sphyrnidae', 'en', 'hammerhead shark'),
  ('Sphyrnidae', 'ja', 'シュモクザメ科'),
  ('Sphyrnidae', 'zh-TW', '雙髻鯊科'),
  ('Mobulidae', 'en', 'manta and devil ray'),
  ('Mobulidae', 'ja', 'イトマキエイ科'),
  ('Mobulidae', 'zh-TW', '蝠鱝科'),
  ('Dasyatidae', 'en', 'stingray'),
  ('Dasyatidae', 'ja', 'アカエイ科'),
  ('Dasyatidae', 'zh-TW', '魟科'),
  ('Myliobatidae', 'en', 'eagle ray'),
  ('Myliobatidae', 'ja', 'トビエイ科'),
  ('Chaetodontidae', 'en', 'butterflyfish'),
  ('Chaetodontidae', 'ja', 'チョウチョウウオ科'),
  ('Chaetodontidae', 'zh-TW', '蝴蝶魚科'),
  ('Pomacanthidae', 'en', 'angelfish'),
  ('Pomacanthidae', 'ja', 'キンチャクダイ科'),
  ('Pomacanthidae', 'zh-TW', '蓋刺魚科'),
  ('Pomacentridae', 'en', 'damselfish'),
  ('Pomacentridae', 'ja', 'スズメダイ科'),
  ('Pomacentridae', 'zh-TW', '雀鯛科'),
  ('Labridae', 'en', 'wrasse'),
  ('Labridae', 'ja', 'ベラ科'),
  ('Labridae', 'zh-TW', '隆頭魚科'),
  ('Scaridae', 'en', 'parrotfish'),
  ('Scaridae', 'ja', 'ブダイ科'),
  ('Scaridae', 'zh-TW', '鸚哥魚科'),
  ('Serranidae', 'en', 'grouper'),
  ('Serranidae', 'ja', 'ハタ科'),
  ('Serranidae', 'zh-TW', '鮨科'),
  ('Muraenidae', 'en', 'moray eel'),
  ('Muraenidae', 'ja', 'ウツボ科'),
  ('Muraenidae', 'zh-TW', '鯙科'),
  ('Scorpaenidae', 'en', 'scorpionfish'),
  ('Scorpaenidae', 'ja', 'フサカサゴ科'),
  ('Scorpaenidae', 'zh-TW', '鮋科'),
  ('Synanceiidae', 'en', 'stonefish'),
  ('Synanceiidae', 'ja', 'オニオコゼ科'),
  ('Synanceiidae', 'zh-TW', '毒鮋科'),
  ('Antennariidae', 'en', 'frogfish'),
  ('Antennariidae', 'ja', 'カエルアンコウ科'),
  ('Antennariidae', 'zh-TW', '躄魚科'),
  ('Syngnathidae', 'en', 'pipefish and seahorse'),
  ('Syngnathidae', 'ja', 'ヨウジウオ科'),
  ('Syngnathidae', 'zh-TW', '海龍科'),
  ('Ostraciidae', 'en', 'boxfish'),
  ('Ostraciidae', 'ja', 'ハコフグ科'),
  ('Ostraciidae', 'zh-TW', '箱魨科'),
  ('Tetraodontidae', 'en', 'pufferfish'),
  ('Tetraodontidae', 'ja', 'フグ科'),
  ('Tetraodontidae', 'zh-TW', '四齒魨科'),
  ('Diodontidae', 'en', 'porcupinefish'),
  ('Diodontidae', 'ja', 'ハリセンボン科'),
  ('Diodontidae', 'zh-TW', '二齒魨科'),
  ('Balistidae', 'en', 'triggerfish'),
  ('Balistidae', 'ja', 'モンガラカワハギ科'),
  ('Balistidae', 'zh-TW', '鱗魨科'),
  ('Acanthuridae', 'en', 'surgeonfish'),
  ('Acanthuridae', 'ja', 'ニザダイ科'),
  ('Acanthuridae', 'zh-TW', '刺尾鯛科'),
  ('Apogonidae', 'en', 'cardinalfish'),
  ('Apogonidae', 'ja', 'テンジクダイ科'),
  ('Apogonidae', 'zh-TW', '天竺鯛科'),
  ('Blenniidae', 'en', 'blenny'),
  ('Blenniidae', 'ja', 'イソギンポ科'),
  ('Blenniidae', 'zh-TW', '鳚科'),
  ('Gobiidae', 'en', 'goby'),
  ('Gobiidae', 'ja', 'ハゼ科'),
  ('Gobiidae', 'zh-TW', '鰕虎科'),
  ('Holocentridae', 'en', 'squirrelfish'),
  ('Holocentridae', 'ja', 'イットウダイ科'),
  ('Holocentridae', 'zh-TW', '金鱗魚科'),
  ('Lutjanidae', 'en', 'snapper'),
  ('Lutjanidae', 'ja', 'フエダイ科'),
  ('Lutjanidae', 'zh-TW', '笛鯛科'),
  ('Haemulidae', 'en', 'sweetlips'),
  ('Haemulidae', 'ja', 'イサキ科'),
  ('Haemulidae', 'zh-TW', '石鱸科'),
  ('Caesionidae', 'en', 'fusilier'),
  ('Caesionidae', 'ja', 'タカサゴ科'),
  ('Caesionidae', 'zh-TW', '烏尾鮗科'),
  ('Siganidae', 'en', 'rabbitfish'),
  ('Siganidae', 'ja', 'アイゴ科'),
  ('Siganidae', 'zh-TW', '臭肚魚科'),
  ('Mullidae', 'en', 'goatfish'),
  ('Mullidae', 'ja', 'ヒメジ科'),
  ('Mullidae', 'zh-TW', '鬚鯛科'),
  ('Carangidae', 'en', 'trevally and jack'),
  ('Carangidae', 'ja', 'アジ科'),
  ('Carangidae', 'zh-TW', '鰺科'),
  ('Sphyraenidae', 'en', 'barracuda'),
  ('Sphyraenidae', 'ja', 'カマス科'),
  ('Sphyraenidae', 'zh-TW', '金梭魚科'),
  ('Loliginidae', 'en', 'squid'),
  ('Loliginidae', 'ja', 'ヤリイカ科'),
  ('Loliginidae', 'zh-TW', '魷魚科'),
  ('Palinuridae', 'en', 'spiny lobster'),
  ('Palinuridae', 'ja', 'イセエビ科'),
  ('Palinuridae', 'zh-TW', '龍蝦科'),
  ('Delphinidae', 'en', 'dolphin'),
  ('Delphinidae', 'ja', 'マイルカ科'),
  ('Delphinidae', 'zh-TW', '海豚科'),
  ('Hippocampus', 'en', 'seahorse'),
  ('Hippocampus', 'ja', 'タツノオトシゴ'),
  ('Hippocampus', 'zh-TW', '海馬'),
  ('Tridacna', 'en', 'giant clam'),
  ('Tridacna', 'ja', 'シャコガイ'),
  ('Tridacna', 'zh-TW', '硨磲貝'),
  ('Acropora', 'en', 'staghorn coral'),
  ('Acropora', 'ja', 'ミドリイシ'),
  ('Acropora', 'zh-TW', '軸孔珊瑚'),
  ('Porites', 'en', 'porites coral'),
  ('Porites', 'ja', 'ハマサンゴ'),
  ('Porites', 'zh-TW', '微孔珊瑚'),
  ('Laticauda', 'en', 'sea krait'),
  ('Laticauda', 'ja', 'エラブウミヘビ'),
  ('Laticauda', 'zh-TW', '闊尾海蛇'),
  ('Chelonia mydas', 'en', 'green sea turtle'),
  ('Chelonia mydas', 'ja', 'アオウミガメ'),
  ('Chelonia mydas', 'zh-TW', '綠蠵龜'),
  ('Eretmochelys imbricata', 'en', 'hawksbill turtle'),
  ('Eretmochelys imbricata', 'ja', 'タイマイ'),
  ('Eretmochelys imbricata', 'zh-TW', '玳瑁'),
  ('Rhincodon typus', 'en', 'whale shark'),
  ('Rhincodon typus', 'ja', 'ジンベエザメ'),
  ('Rhincodon typus', 'zh-TW', '鯨鯊'),
  ('Triaenodon obesus', 'en', 'whitetip reef shark'),
  ('Triaenodon obesus', 'ja', 'ネムリブカ'),
  ('Triaenodon obesus', 'zh-TW', '灰三齒鯊'),
  ('Carcharhinus melanopterus', 'en', 'blacktip reef shark'),
  ('Carcharhinus melanopterus', 'ja', 'ツマグロ'),
  ('Carcharhinus melanopterus', 'zh-TW', '烏翅真鯊'),
  ('Sphyrna lewini', 'en', 'scalloped hammerhead'),
  ('Sphyrna lewini', 'ja', 'アカシュモクザメ'),
  ('Sphyrna lewini', 'zh-TW', '紅肉丫髻鮫'),
  ('Mobula alfredi', 'en', 'reef manta ray'),
  ('Mobula alfredi', 'ja', 'ナンヨウマンタ'),
  ('Mobula alfredi', 'zh-TW', '阿氏前口蝠鱝'),
  ('Mobula birostris', 'en', 'giant manta ray'),
  ('Mobula birostris', 'ja', 'オニイトマキエイ'),
  ('Mobula birostris', 'zh-TW', '雙吻前口蝠鱝'),
  ('Taeniura lymma', 'en', 'bluespotted ribbontail ray'),
  ('Taeniura lymma', 'zh-TW', '藍點魟'),
  ('Aetobatus ocellatus', 'en', 'ocellated eagle ray'),
  ('Aetobatus ocellatus', 'ja', 'マダラトビエイ'),
  ('Amphiprion clarkii', 'en', 'Clark''s anemonefish'),
  ('Amphiprion clarkii', 'ja', 'クマノミ'),
  ('Amphiprion clarkii', 'zh-TW', '克氏海葵魚'),
  ('Amphiprion ocellaris', 'en', 'clown anemonefish'),
  ('Amphiprion ocellaris', 'ja', 'カクレクマノミ'),
  ('Amphiprion ocellaris', 'zh-TW', '眼斑海葵魚'),
  ('Pomacanthus imperator', 'en', 'emperor angelfish'),
  ('Pomacanthus imperator', 'ja', 'タテジマキンチャクダイ'),
  ('Pomacanthus imperator', 'zh-TW', '主刺蓋魚'),
  ('Chaetodon auriga', 'en', 'threadfin butterflyfish'),
  ('Chaetodon auriga', 'ja', 'トゲチョウチョウウオ'),
  ('Chaetodon auriga', 'zh-TW', '揚幡蝴蝶魚'),
  ('Heniochus acuminatus', 'en', 'pennant coralfish'),
  ('Heniochus acuminatus', 'ja', 'ハタタテダイ'),
  ('Heniochus acuminatus', 'zh-TW', '白吻雙帶立旗鯛'),
  ('Zanclus cornutus', 'en', 'moorish idol'),
  ('Zanclus cornutus', 'ja', 'ツノダシ'),
  ('Zanclus cornutus', 'zh-TW', '角鐮魚'),
  ('Cheilinus undulatus', 'en', 'humphead wrasse'),
  ('Cheilinus undulatus', 'ja', 'メガネモチノウオ'),
  ('Cheilinus undulatus', 'zh-TW', '曲紋唇魚'),
  ('Bolbometopon muricatum', 'en', 'bumphead parrotfish'),
  ('Bolbometopon muricatum', 'ja', 'カンムリブダイ'),
  ('Bolbometopon muricatum', 'zh-TW', '隆頭鸚哥魚'),
  ('Plectropomus leopardus', 'en', 'leopard coral grouper'),
  ('Plectropomus leopardus', 'ja', 'スジアラ'),
  ('Plectropomus leopardus', 'zh-TW', '豹紋鰓棘鱸'),
  ('Gymnothorax javanicus', 'en', 'giant moray'),
  ('Gymnothorax javanicus', 'ja', 'ドクウツボ'),
  ('Gymnothorax javanicus', 'zh-TW', '爪哇裸胸鯙'),
  ('Pterois volitans', 'en', 'red lionfish'),
  ('Pterois volitans', 'ja', 'ハナミノカサゴ'),
  ('Pterois volitans', 'zh-TW', '魔鬼簑鮋'),
  ('Synanceia verrucosa', 'en', 'reef stonefish'),
  ('Synanceia verrucosa', 'ja', 'オニダルマオコゼ'),
  ('Synanceia verrucosa', 'zh-TW', '玫瑰毒鮋'),
  ('Ostracion cubicus', 'en', 'yellow boxfish'),
  ('Ostracion cubicus', 'ja', 'ミナミハコフグ'),
  ('Ostracion cubicus', 'zh-TW', '粒突箱魨'),
  ('Mola mola', 'en', 'ocean sunfish'),
  ('Mola mola', 'ja', 'マンボウ'),
  ('Mola mola', 'zh-TW', '翻車魚'),
  ('Sepioteuthis lessoniana', 'en', 'bigfin reef squid'),
  ('Sepioteuthis lessoniana', 'ja', 'アオリイカ'),
  ('Sepioteuthis lessoniana', 'zh-TW', '軟絲'),
  ('Hexabranchus sanguineus', 'en', 'Spanish dancer'),
  ('Hexabranchus sanguineus', 'ja', 'ミカドウミウシ'),
  ('Hexabranchus sanguineus', 'zh-TW', '西班牙舞娘'),
  ('Acanthaster planci', 'en', 'crown-of-thorns starfish'),
  ('Acanthaster planci', 'ja', 'オニヒトデ'),
  ('Acanthaster planci', 'zh-TW', '棘冠海星'),
  ('Stenopus hispidus', 'en', 'banded coral shrimp'),
  ('Stenopus hispidus', 'ja', 'オトヒメエビ'),
  ('Stenopus hispidus', 'zh-TW', '油彩蠟膜蝦'),
  ('Megaptera novaeangliae', 'en', 'humpback whale'),
  ('Megaptera novaeangliae', 'ja', 'ザトウクジラ'),
  ('Megaptera novaeangliae', 'zh-TW', '大翅鯨'),
  ('Physeter macrocephalus', 'en', 'sperm whale'),
  ('Physeter macrocephalus', 'ja', 'マッコウクジラ'),
  ('Physeter macrocephalus', 'zh-TW', '抹香鯨')
) as v(scientific_name, lang, name)
join public.taxa t on lower(t.scientific_name) = lower(v.scientific_name);
